---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: kube-ip-purge
  name: kube-ip-purge
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-ip-purge
  template:
    metadata:
      labels:
        app: kube-ip-purge
    spec:
      containers:
      - name: kube-ip-purge
        image: quay.io/reactiveops/kube-ip-purge:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
